from __future__ import annotations

ACTIVITY_VECTORS = {
    "build": {
        "display_name": "Invest / Build / Marry",
        "officer_good": ["Ding", "Cheng", "Man"],
        "officer_bad": ["Po", "Bi", "Wei"],
    },
    "contract": {
        "display_name": "Sign Contracts / Launch",
        "officer_good": ["Jian", "Cheng", "Kai"],
        "officer_bad": ["Po", "Bi", "Wei"],
    },
    "release": {
        "display_name": "Medical / Cleansing / Release",
        "officer_good": ["Chu", "Po", "Ping"],
        "officer_bad": ["Cheng", "Jian"],
    },
    "travel": {
        "display_name": "Travel / Explore",
        "officer_good": ["Kai", "Zhi", "Shou"],
        "officer_bad": ["Po", "Bi", "Wei"],
    },
}

VEDIC_RULES = {
    "job_start": {
        "display_name": "Corporate Job Entry & Contracts",
        "default_activity_vector": "contract",
        "vara_good": [4, 5, 6],
        "vara_neutral": [2],
        "tithi_good": [2, 7, 10, 15],
        "tithi_neutral": [1, 3, 5, 11, 13],
        "tithi_blocked": [4, 9, 14],
        "nakshatra_good": [4, 12, 21, 27],
        "yoga_blocked": [17, 27],
        "chinese_officer_good": ["Jian", "Cheng", "Kai"],
        "chinese_officer_bad": ["Po", "Bi", "Wei"],
        "chinese_mansion": "Horn (Jiao)",
    },
    "real_estate": {
        "display_name": "Property & Land Registration",
        "default_activity_vector": "build",
        "vara_good": [3, 5, 6],
        "vara_neutral": [5, 6],
        "tithi_good": [3, 5, 10, 11],
        "tithi_neutral": [1, 2, 6, 7],
        "tithi_blocked": [4, 9, 14],
        "nakshatra_good": [4, 5, 8],
        "yoga_blocked": [17, 27],
        "chinese_officer_good": ["Ding", "Cheng", "Man"],
        "chinese_officer_bad": ["Po", "Wei", "Bi"],
        "chinese_mansion": "Room (Fang)",
    },
    "love_marriage": {
        "display_name": "Engagement & Marital Rites",
        "default_activity_vector": "build",
        "vara_good": [2, 6],
        "vara_neutral": [1, 5],
        "tithi_good": [5, 7, 13, 15],
        "tithi_neutral": [2, 3, 10, 11],
        "tithi_blocked": [4, 9, 14],
        "nakshatra_good": [4, 5, 15, 27],
        "yoga_blocked": [17, 27],
        "chinese_officer_good": ["Cheng", "Ding", "Man"],
        "chinese_officer_bad": ["Po", "Bi"],
        "chinese_mansion": "Heart (Xin)",
    },
    "litigation": {
        "display_name": "Legal Filings & Dispute Resolution",
        "default_activity_vector": "release",
        "vara_good": [3, 7],
        "vara_neutral": [2],
        "tithi_good": [4, 9, 14],
        "tithi_neutral": [6, 11],
        "tithi_blocked": [],
        "nakshatra_good": [2, 18],
        "yoga_blocked": [],
        "chinese_officer_good": ["Chu", "Po"],
        "chinese_officer_bad": ["Cheng", "Kai"],
        "chinese_mansion": "Net (Bi)",
    },
    "medical_surgery": {
        "display_name": "Elective Medical Procedures",
        "default_activity_vector": "release",
        "vara_good": [1, 5],
        "vara_neutral": [3, 4],
        "tithi_good": [2, 6, 11],
        "tithi_neutral": [7, 12],
        "tithi_blocked": [15, 30],
        "nakshatra_good": [1, 13, 22],
        "yoga_blocked": [17, 27],
        "chinese_officer_good": ["Chu", "Ping"],
        "chinese_officer_bad": ["Cheng", "Jian"],
        "chinese_mansion": "Pleiades (Mao)",
    },
    "digital_launch": {
        "display_name": "Software & Media Product Release",
        "default_activity_vector": "contract",
        "vara_good": [4, 6],
        "vara_neutral": [5],
        "tithi_good": [5, 10, 15],
        "tithi_neutral": [2, 7, 11],
        "tithi_blocked": [4, 9, 14],
        "nakshatra_good": [6, 14, 24],
        "yoga_blocked": [17, 27],
        "chinese_officer_good": ["Kai", "Cheng"],
        "chinese_officer_bad": ["Po", "Bi", "Wei"],
        "chinese_mansion": "Rooftop (Wei)",
    },
    "agriculture": {
        "display_name": "Agriculture & New Cultivation",
        "default_activity_vector": "build",
        "vara_good": [2, 5],
        "vara_neutral": [1, 4],
        "tithi_good": [1, 3, 8, 10],
        "tithi_neutral": [5, 7],
        "tithi_blocked": [4, 9, 14],
        "nakshatra_good": [3, 4, 17],
        "yoga_blocked": [17, 27],
        "chinese_officer_good": ["Man", "Shou"],
        "chinese_officer_bad": ["Po", "Bi"],
        "chinese_mansion": "Willow (Liu)",
    },
    "debt_clearance": {
        "display_name": "Debt Settlement & Financial Closure",
        "default_activity_vector": "release",
        "vara_good": [3],
        "vara_neutral": [7],
        "tithi_good": [4, 9],
        "tithi_neutral": [14],
        "tithi_blocked": [15, 30],
        "nakshatra_good": [13, 24],
        "yoga_blocked": [],
        "chinese_officer_good": ["Po", "Chu"],
        "chinese_officer_bad": ["Cheng", "Man"],
        "chinese_mansion": "Ghost (Gui)",
    },
    "travel": {
        "display_name": "Long-Distance Travel & Logistics",
        "default_activity_vector": "travel",
        "vara_good": [5, 6],
        "vara_neutral": [4],
        "tithi_good": [2, 7, 11],
        "tithi_neutral": [3, 5],
        "tithi_blocked": [4, 9, 14],
        "nakshatra_good": [1, 7, 22, 27],
        "yoga_blocked": [17, 27],
        "chinese_officer_good": ["Kai", "Zhi"],
        "chinese_officer_bad": ["Po", "Bi", "Wei"],
        "chinese_mansion": "Stride (Kui)",
    },
    "creative_arts": {
        "display_name": "Creative Launch & Performance",
        "default_activity_vector": "travel",
        "vara_good": [6],
        "vara_neutral": [2, 4],
        "tithi_good": [3, 5, 13],
        "tithi_neutral": [7, 10],
        "tithi_blocked": [4, 9, 14, 30],
        "nakshatra_good": [11, 14, 27],
        "yoga_blocked": [17, 27],
        "chinese_officer_good": ["Shou", "Kai"],
        "chinese_officer_bad": ["Po", "Wei"],
        "chinese_mansion": "Bow (Zhang)",
    },
}

CHINESE_RULES = {
    slug: {
        "display_name": rule["display_name"],
        "default_activity_vector": rule["default_activity_vector"],
        "officer_good": list(rule["chinese_officer_good"]),
        "officer_bad": list(rule["chinese_officer_bad"]),
        "lunar_mansion": rule["chinese_mansion"],
    }
    for slug, rule in VEDIC_RULES.items()
}

DAY_OFFICERS = [
    {"slug": "Jian", "label": "Establish"},
    {"slug": "Chu", "label": "Remove"},
    {"slug": "Man", "label": "Full"},
    {"slug": "Ping", "label": "Balance"},
    {"slug": "Ding", "label": "Stable"},
    {"slug": "Zhi", "label": "Initiate"},
    {"slug": "Po", "label": "Destruction"},
    {"slug": "Wei", "label": "Danger"},
    {"slug": "Cheng", "label": "Success"},
    {"slug": "Shou", "label": "Receive"},
    {"slug": "Kai", "label": "Open"},
    {"slug": "Bi", "label": "Close"},
]

CHINESE_ANIMALS = [
    "Rat",
    "Ox",
    "Tiger",
    "Rabbit",
    "Dragon",
    "Snake",
    "Horse",
    "Goat",
    "Monkey",
    "Rooster",
    "Dog",
    "Pig",
]

ZODIAC_CLASHES = {
    "Rat": "Horse",
    "Ox": "Goat",
    "Tiger": "Monkey",
    "Rabbit": "Rooster",
    "Dragon": "Dog",
    "Snake": "Pig",
    "Horse": "Rat",
    "Goat": "Ox",
    "Monkey": "Tiger",
    "Rooster": "Rabbit",
    "Dog": "Dragon",
    "Pig": "Snake",
}

LUNAR_MANSIONS = [
    "Horn (Jiao)",
    "Neck (Kang)",
    "Root (Di)",
    "Room (Fang)",
    "Heart (Xin)",
    "Tail (Wei)",
    "Basket (Ji)",
    "Fight (Dou)",
    "Ox (Niu)",
    "Girl (Nu)",
    "Emptiness (Xu)",
    "Rooftop (Wei)",
    "Encampment (Shi)",
    "Wall (Bi)",
    "Stride (Kui)",
    "Mound (Lou)",
    "Stomach (Wei)",
    "Pleiades (Mao)",
    "Net (Bi)",
    "Beak (Zi)",
    "Triple Stars (Shen)",
    "Well (Jing)",
    "Ghost (Gui)",
    "Willow (Liu)",
    "Star (Xing)",
    "Extended Net (Zhang)",
    "Wings (Yi)",
    "Chariot (Zhen)",
]

SOLAR_MONTH_BRANCH_OFFSETS = {
    1: 1,
    2: 2,
    3: 3,
    4: 4,
    5: 5,
    6: 6,
    7: 7,
    8: 8,
    9: 9,
    10: 10,
    11: 11,
    12: 0,
}

CATEGORY_INTENT_PHRASES = {
    "job_start": "career moves and contract signing",
    "real_estate": "property registration and land matters",
    "love_marriage": "engagements and marital rites",
    "litigation": "legal filings and dispute work",
    "medical_surgery": "medical procedures and recovery planning",
    "digital_launch": "product launches and media releases",
    "agriculture": "cultivation and land activation",
    "debt_clearance": "debt settlement and financial closure",
    "travel": "travel, logistics, and movement",
    "creative_arts": "creative launches and performances",
}

RETROGRADE_SENSITIVE_CATEGORIES = {"job_start", "digital_launch", "travel"}
HARD_BLOCK_OFFICERS = {"Po", "Bi"}
