from reportlab.lib.pagesizes import letter, A4
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from reportlab.pdfgen import canvas
from io import BytesIO
from datetime import datetime

def create_header_footer(canvas_obj, doc):
    """Add header and footer to each page"""
    canvas_obj.saveState()
    
    # Header
    canvas_obj.setFont('Helvetica-Bold', 16)
    canvas_obj.setFillColor(colors.HexColor('#C5A059'))
    canvas_obj.drawString(inch, letter[1] - 0.5*inch, "Cosmic Wisdom")
    
    # Footer
    canvas_obj.setFont('Helvetica', 9)
    canvas_obj.setFillColor(colors.grey)
    canvas_obj.drawString(inch, 0.5*inch, "Generated by Cosmic Wisdom - Your Personal Astrology Guide")
    canvas_obj.drawRightString(letter[0] - inch, 0.5*inch, f"Page {doc.page}")
    
    canvas_obj.restoreState()

def generate_birth_chart_pdf(profile, report_content):
    """Generate PDF for Birth Chart report"""
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=1*inch, bottomMargin=0.75*inch)
    
    # Styles
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#C5A059'),
        spaceAfter=30,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold'
    )
    
    subtitle_style = ParagraphStyle(
        'CustomSubtitle',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=colors.HexColor('#4A3728'),
        spaceAfter=20,
        alignment=TA_CENTER
    )
    
    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['BodyText'],
        fontSize=11,
        leading=16,
        alignment=TA_JUSTIFY,
        spaceAfter=12
    )
    
    # Build content
    story = []
    
    # Title
    story.append(Paragraph("Birth Chart Analysis", title_style))
    story.append(Spacer(1, 0.2*inch))
    
    # Personal Info Table
    data = [
        ['Name:', profile['name']],
        ['Date of Birth:', profile['date_of_birth']],
        ['Time of Birth:', profile['time_of_birth']],
        ['Place of Birth:', profile['location']],
        ['Report Generated:', datetime.now().strftime('%B %d, %Y')]
    ]
    
    table = Table(data, colWidths=[2*inch, 4*inch])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#F9F5F0')),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.HexColor('#2D241E')),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E6DCCF')),
        ('PADDING', (0, 0), (-1, -1), 8),
    ]))
    
    story.append(table)
    story.append(Spacer(1, 0.4*inch))
    
    # Report Content
    story.append(Paragraph("Comprehensive Vedic Astrology Analysis", subtitle_style))
    story.append(Spacer(1, 0.2*inch))
    
    # Split content into paragraphs
    paragraphs = report_content.split('\n\n')
    for para in paragraphs:
        if para.strip():
            story.append(Paragraph(para.strip(), body_style))
    
    # Build PDF
    doc.build(story, onFirstPage=create_header_footer, onLaterPages=create_header_footer)
    
    buffer.seek(0)
    return buffer

def generate_kundali_milan_pdf(person1, person2, compatibility_score, analysis):
    """Generate PDF for Kundali Milan report"""
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=1*inch, bottomMargin=0.75*inch)
    
    # Styles
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#C5A059'),
        spaceAfter=30,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold'
    )
    
    score_style = ParagraphStyle(
        'ScoreStyle',
        parent=styles['Heading1'],
        fontSize=36,
        textColor=colors.HexColor('#C5A059'),
        spaceAfter=10,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold'
    )
    
    subtitle_style = ParagraphStyle(
        'CustomSubtitle',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=colors.HexColor('#4A3728'),
        spaceAfter=20,
        alignment=TA_CENTER
    )
    
    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['BodyText'],
        fontSize=11,
        leading=16,
        alignment=TA_JUSTIFY,
        spaceAfter=12
    )
    
    # Build content
    story = []
    
    # Title
    story.append(Paragraph("Kundali Milan - Marriage Compatibility Report", title_style))
    story.append(Spacer(1, 0.3*inch))
    
    # Compatibility Score
    story.append(Paragraph(f"{compatibility_score}/36", score_style))
    
    # Score interpretation
    if compatibility_score >= 28:
        score_text = "Excellent Match"
    elif compatibility_score >= 24:
        score_text = "Very Good Match"
    elif compatibility_score >= 18:
        score_text = "Good Match"
    else:
        score_text = "Average Match"
    
    story.append(Paragraph(score_text, subtitle_style))
    story.append(Spacer(1, 0.3*inch))
    
    # Person Details Tables
    data1 = [
        ['Person 1 Details', ''],
        ['Name:', person1['name']],
        ['Date of Birth:', person1['date_of_birth']],
        ['Time of Birth:', person1['time_of_birth']],
        ['Place of Birth:', person1['location']]
    ]
    
    data2 = [
        ['Person 2 Details', ''],
        ['Name:', person2['name']],
        ['Date of Birth:', person2['date_of_birth']],
        ['Time of Birth:', person2['time_of_birth']],
        ['Place of Birth:', person2['location']]
    ]
    
    table1 = Table(data1, colWidths=[2*inch, 3*inch])
    table1.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#C5A059')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('BACKGROUND', (0, 1), (0, -1), colors.HexColor('#F9F5F0')),
        ('TEXTCOLOR', (0, 1), (-1, -1), colors.HexColor('#2D241E')),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTNAME', (0, 1), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E6DCCF')),
        ('PADDING', (0, 0), (-1, -1), 8),
        ('SPAN', (0, 0), (-1, 0)),
    ]))
    
    table2 = Table(data2, colWidths=[2*inch, 3*inch])
    table2.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#C5A059')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('BACKGROUND', (0, 1), (0, -1), colors.HexColor('#F9F5F0')),
        ('TEXTCOLOR', (0, 1), (-1, -1), colors.HexColor('#2D241E')),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTNAME', (0, 1), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E6DCCF')),
        ('PADDING', (0, 0), (-1, -1), 8),
        ('SPAN', (0, 0), (-1, 0)),
    ]))
    
    story.append(table1)
    story.append(Spacer(1, 0.2*inch))
    story.append(table2)
    story.append(Spacer(1, 0.4*inch))
    
    # Analysis
    story.append(Paragraph("Detailed Compatibility Analysis", subtitle_style))
    story.append(Spacer(1, 0.2*inch))
    
    # Split content into paragraphs
    paragraphs = analysis.split('\n\n')
    for para in paragraphs:
        if para.strip():
            story.append(Paragraph(para.strip(), body_style))
    
    # Report date
    story.append(Spacer(1, 0.3*inch))
    story.append(Paragraph(f"Report Generated: {datetime.now().strftime('%B %d, %Y')}", 
                          ParagraphStyle('Footer', parent=styles['Normal'], fontSize=9, 
                                       textColor=colors.grey, alignment=TA_CENTER)))
    
    # Build PDF
    doc.build(story, onFirstPage=create_header_footer, onLaterPages=create_header_footer)
    
    buffer.seek(0)
    return buffer