export const ANGEL_NUMBER_ORDER = [
  '111',
  '222',
  '333',
  '444',
  '555',
  '666',
  '777',
  '888',
  '999',
  '1111',
  '1212',
  '1234',
  '2222',
  '3333',
];

export const ANGEL_NUMBERS = {
  '111': {
    number: '111',
    title: '111 Angel Number',
    tagline: 'New Beginnings and Manifestation',
    meaning: 'Angel number 111 is a powerful manifestation code. When you see 111, the Universe is signalling that your thoughts are rapidly manifesting into reality. This is a call to align your mind with your highest intentions.',
    spiritual: 'In Vedic numerology, 1 is the number of the Sun: leadership, willpower, and originality. Triple 1 amplifies this energy threefold, indicating a portal of creation and new beginnings.',
    love: 'In love, 111 signals the start of something new: a new relationship, a fresh chapter in an existing one, or a renewed sense of self-love. It encourages authenticity in your connections.',
    career: 'For career, 111 is a green light for new ventures, leadership roles, and bold decisions. Your instincts are aligned with opportunity right now.',
    what_to_do: [
      'Write down your intentions and desires because the Universe is listening.',
      'Avoid negative thought loops because your focus is amplifying now.',
      'Take one bold step toward your goal today.',
      'Notice repeating signs and synchronicities.',
    ],
    numerology_base: 3,
    vedic_connection: 'Surya (Sun): soul, authority, life purpose',
    colour: 'from-amber-500/20 to-yellow-500/10',
    icon: 'Sunrise',
  },
  '222': {
    number: '222',
    title: '222 Angel Number',
    tagline: 'Balance, Partnership and Divine Timing',
    meaning: 'Angel number 222 carries the energy of balance, harmony, and faith. Seeing 222 is a message to trust the process. Everything is unfolding in divine timing, even when it does not feel that way.',
    spiritual: 'In Vedic numerology, 2 is ruled by Chandra (Moon): the mind, emotions, and relationships. Triple 2 deepens intuition and emphasises patience in partnerships.',
    love: '222 is one of the most powerful love angel numbers. It signals that your relationship is divinely supported, or that a significant partnership is approaching. Trust the connection you feel.',
    career: 'For career, 222 advises patience and collaboration. Partnerships formed now carry lasting value. Avoid forcing outcomes because timing is everything.',
    what_to_do: [
      'Practice patience because your manifestation is closer than it feels.',
      'Nurture your relationships and partnerships.',
      'Trust your intuition about people and situations.',
      'Journal recurring dreams or feelings.',
    ],
    numerology_base: 6,
    vedic_connection: 'Chandra (Moon): emotions, mind, relationship cycles',
    colour: 'from-blue-500/20 to-indigo-500/10',
    icon: 'Moon',
  },
  '333': {
    number: '333',
    title: '333 Angel Number',
    tagline: 'Creative Expression and Ascended Guidance',
    meaning: 'Angel number 333 signals that you are supported by elevated wisdom and creative force. Seeing 333 reminds you to express your truth, trust your gifts, and let expansion happen through courage.',
    spiritual: 'In Vedic numerology, 3 is ruled by Guru (Jupiter): wisdom, expansion, and spiritual growth. Triple 3 is a call to embrace creativity and deepen your learning path.',
    love: '333 in love encourages open, joyful communication. It is a sign to express your feelings, bring playfulness into your relationship, and allow love to grow naturally.',
    career: 'For career, 333 points to creative breakthroughs and meaningful expansion. This is a strong period to share ideas, teach, build, and trust that your talents are valuable.',
    what_to_do: [
      'Express yourself creatively through writing, art, music, or teaching.',
      'Speak your truth with warmth and clarity.',
      'Expand your spiritual practice through study or meditation.',
      'Say yes to growth opportunities that feel aligned.',
    ],
    numerology_base: 9,
    vedic_connection: 'Guru (Jupiter): wisdom, expansion, divine grace',
    colour: 'from-purple-500/20 to-violet-500/10',
    icon: 'Crystal',
  },
  '444': {
    number: '444',
    title: '444 Angel Number',
    tagline: 'Protection, Stability and Divine Support',
    meaning: 'Angel number 444 is a message of profound protection and stability. Your guides are surrounding you with support. This is one of the most reassuring angel numbers to receive.',
    spiritual: 'In Vedic numerology, 4 resonates with Rahu: ambition, transformation, and the karmic path. Triple 4 grounds divine energy into practical reality and gives structure to your next chapter.',
    love: '444 in love points toward a stable, protected connection. If you are in a relationship, your bond has strong support. If you are single, 444 signals grounded love on the way.',
    career: 'For career, 444 means your hard work is building something solid and lasting. Your foundations are strengthening, so keep going with discipline.',
    what_to_do: [
      'Acknowledge how far you have already come.',
      'Build systems and routines that support your long-term goals.',
      'Choose stability in your relationships and environment.',
      'Trust that you are protected on your path.',
    ],
    numerology_base: 3,
    vedic_connection: 'Rahu: ambition, karmic direction, transformation',
    colour: 'from-green-500/20 to-emerald-500/10',
    icon: 'Shield',
  },
  '555': {
    number: '555',
    title: '555 Angel Number',
    tagline: 'Major Change and Transformation',
    meaning: 'Angel number 555 is a powerful sign of change. Major transformation is either arriving or already in motion. This is not a moment to resist. It is a moment to move with life.',
    spiritual: 'In Vedic numerology, 5 is ruled by Budha (Mercury): communication, adaptability, and movement. Triple 5 amplifies change and rewards flexibility.',
    love: '555 in love suggests a relationship chapter is transforming. That could mean a powerful new connection, a relationship evolving to a new level, or an old pattern ending.',
    career: 'For career, 555 often appears before a professional pivot such as a new role, city, industry, or direction. The old chapter is closing and the new one is gathering speed.',
    what_to_do: [
      'Release attachment to how things were supposed to look.',
      'Welcome change as a sign of growth rather than loss.',
      'Make decisions from values, not fear.',
      'Document this transition because it matters.',
    ],
    numerology_base: 6,
    vedic_connection: 'Budha (Mercury): intelligence, adaptability, communication',
    colour: 'from-orange-500/20 to-red-500/10',
    icon: 'Whirlwind',
  },
  '666': {
    number: '666',
    title: '666 Angel Number',
    tagline: 'Balance, Home and Nurturing',
    meaning: 'Despite its pop-culture reputation, 666 in angel number tradition is a beautiful number of balance, home, family, and nurturing. It is a call to return to what matters most.',
    spiritual: 'In Vedic numerology, 6 is ruled by Shukra (Venus): love, beauty, harmony, and creative expression. Triple 6 amplifies care, relationship healing, and devotion to your environment.',
    love: '666 in love is deeply nurturing energy. It asks for compassion, care, and attention to home life, family, and emotional safety.',
    career: 'For career, 666 suggests your work-life balance needs attention. Reconnect with why you work and whether your life is receiving enough of your presence.',
    what_to_do: [
      'Spend meaningful time with family and loved ones.',
      'Create more beauty and calm in your home environment.',
      'Reconnect with creative pursuits you have neglected.',
      'Balance ambition with presence.',
    ],
    numerology_base: 9,
    vedic_connection: 'Shukra (Venus): love, beauty, harmony, material abundance',
    colour: 'from-pink-500/20 to-rose-500/10',
    icon: 'Home',
  },
  '777': {
    number: '777',
    title: '777 Angel Number',
    tagline: 'Spiritual Awakening and Divine Luck',
    meaning: 'Angel number 777 is one of the strongest signals of spiritual alignment. It points to awakening, intuition, and deep soul-level confirmation that you are on the right path.',
    spiritual: 'In Vedic numerology, 7 is ruled by Ketu: spirituality, liberation, and detachment from the material. Triple 7 is a profound invitation to deepen your spiritual practice.',
    love: '777 in love can point to a spiritually significant connection, a relationship that catalyses growth, or a deepening of sacred trust with your partner.',
    career: 'For career, 777 signals that your work is aligning more closely with your soul path. Success now tends to feel meaningful, not merely impressive.',
    what_to_do: [
      'Deepen your spiritual practice through meditation, study, or silence.',
      'Trust your intuition completely at this time.',
      'Pay attention to synchronicities because they are guidance.',
      'Share your spiritual gifts through teaching, writing, or service.',
    ],
    numerology_base: 3,
    vedic_connection: 'Ketu: spiritual liberation, past-life wisdom, moksha',
    colour: 'from-violet-500/20 to-purple-500/10',
    icon: 'Star',
  },
  '888': {
    number: '888',
    title: '888 Angel Number',
    tagline: 'Abundance, Karma and Financial Flow',
    meaning: 'Angel number 888 is the number of abundant return. It signals that prosperity, support, and karmic reward are beginning to flow more visibly into your life.',
    spiritual: 'In Vedic numerology, 8 is ruled by Shani (Saturn): karma, discipline, and long-term reward. Triple 8 often reflects material results arriving after sustained effort.',
    love: '888 in love signals a relationship of abundance and mutual growth. Emotional stability and material steadiness are supporting the bond.',
    career: 'For career, 888 is one of the strongest symbols of financial progress, recognition, and reward. Your disciplined effort is delivering results.',
    what_to_do: [
      'Receive abundance without deflecting it.',
      'Review financial plans, savings, and investments.',
      'Express gratitude for what is already working.',
      'Share generously because abundance grows in circulation.',
    ],
    numerology_base: 6,
    vedic_connection: 'Shani (Saturn): karma, discipline, long-term reward',
    colour: 'from-yellow-600/20 to-amber-500/10',
    icon: 'Wealth',
  },
  '999': {
    number: '999',
    title: '999 Angel Number',
    tagline: 'Completion, Release and New Cycle',
    meaning: 'Angel number 999 signals the end of a major life cycle. A chapter is closing, and the healthiest response is release. Something new is preparing to begin on the other side of completion.',
    spiritual: 'In Vedic numerology, 9 resonates with Mangal (Mars): courage, endings, and decisive transformation. Triple 9 intensifies completion energy.',
    love: '999 in love points to the completion of a relationship pattern. That may be a full ending, or it may be the healing of an old dynamic inside an existing connection.',
    career: 'For career, 999 often marks the closing of a role, project, or professional identity. Do not cling to the chapter that is already complete.',
    what_to_do: [
      'Finish unfinished conversations and projects.',
      'Release grudges, old stories, and patterns that no longer serve you.',
      'Honour what this chapter taught you.',
      'Trust that endings are making room for something better.',
    ],
    numerology_base: 9,
    vedic_connection: 'Mangal (Mars): courage, completion, transformation',
    colour: 'from-red-500/20 to-rose-500/10',
    icon: 'Cycle',
  },
  '1111': {
    number: '1111',
    title: '1111 Angel Number',
    tagline: 'Awakening Portal and Manifestation Gateway',
    meaning: '1111 is the master angel number and one of the most recognised awakening signs. Seeing 11:11 often feels like a portal opening where your thoughts carry amplified manifesting power.',
    spiritual: '1111 reduces to 4, which relates to foundation, but its quadruple 1 structure carries an intensified field of creation energy. It is the classic wake-up number.',
    love: '1111 in love is often read as a twin flame or fated-connection marker. If you repeatedly see 1111 around thoughts of someone, pay attention to what the connection is teaching you.',
    career: 'For career, 1111 is a manifestation portal. Set your intentions clearly and take aligned action because new professional beginnings are close.',
    what_to_do: [
      'Set an intention when you see 11:11.',
      'Write down your goals because they are amplifying now.',
      'Notice what you were thinking in the moment you saw it.',
      'Begin the chapter or conversation you have been delaying.',
    ],
    numerology_base: 4,
    vedic_connection: 'Surya (Sun) amplified fourfold: a master creation portal',
    colour: 'from-yellow-500/20 to-amber-500/10',
    icon: 'Portal',
  },
  '1212': {
    number: '1212',
    title: '1212 Angel Number',
    tagline: 'Divine Alignment and Spiritual Growth',
    meaning: 'Angel number 1212 signals that you are moving in divine alignment. The alternating energies of 1 and 2 balance initiative with trust, action with patience, and intention with intuition.',
    spiritual: '1212 combines solar 1 energy with lunar 2 energy. In Vedic terms, it is a reminder to harmonise conscious will with inner sensitivity.',
    love: '1212 in love is a strong alignment signal. The relationship you are in, or the one approaching, is asking for both courage and emotional maturity.',
    career: 'For career, 1212 suggests your current path is becoming more aligned with your real purpose. Keep moving forward while staying receptive.',
    what_to_do: [
      'Trust that you are where you need to be.',
      'Balance drive with patience.',
      'Nurture both personal and professional relationships.',
      'Meditate on your next step because the answer is close.',
    ],
    numerology_base: 6,
    vedic_connection: 'Surya and Chandra in balance: intention meets intuition',
    colour: 'from-sky-500/20 to-blue-500/10',
    icon: 'Balance',
  },
  '1234': {
    number: '1234',
    title: '1234 Angel Number',
    tagline: 'Step-by-Step Progress and Divine Order',
    meaning: 'Angel number 1234 is the sequence of orderly progress. It reminds you that growth is happening in the right order and that each step matters.',
    spiritual: 'The sequence 1-2-3-4 reflects four stages of manifestation: intention, intuition, action, and foundation. You are being guided through a structured unfolding.',
    love: '1234 in love signals a relationship that is progressing naturally and meaningfully. There is no need to rush what is already growing in the right order.',
    career: 'For career, 1234 says trust the process. Something significant is being built step by step, and skipping stages would weaken the outcome.',
    what_to_do: [
      'Focus on the next step rather than the whole staircase.',
      'Trust the order of events unfolding around you.',
      'Complete what you started before chasing something new.',
      'Celebrate each small piece of progress.',
    ],
    numerology_base: 1,
    vedic_connection: 'Sequential planetary energy aligned through purposeful progression',
    colour: 'from-emerald-500/20 to-teal-500/10',
    icon: 'Signal',
  },
  '2222': {
    number: '2222',
    title: '2222 Angel Number',
    tagline: 'Master Balance and Profound Patience',
    meaning: 'Angel number 2222 is the master balance code. It magnifies the patience, trust, and divine timing of 222 into something more enduring and materially grounded.',
    spiritual: '2222 carries master-builder undertones. In Vedic language, it extends lunar sensitivity into something capable of creating stable, lasting reality.',
    love: '2222 in love signals a deeply meaningful connection that asks for patience, mutual trust, and careful nurturing. It often points toward lasting partnership energy.',
    career: 'For career, 2222 suggests you are building one of your most important long-term achievements. Stay patient and do not walk away too early.',
    what_to_do: [
      'Strengthen your practice of patience and faith.',
      'Look for balance in every area of life.',
      'Give extra care to the relationships that matter most.',
      'Journal what you are building and why it matters.',
    ],
    numerology_base: 8,
    vedic_connection: 'Chandra (Moon) amplified: intuition, partnership, patient creation',
    colour: 'from-indigo-500/20 to-blue-600/10',
    icon: 'Ocean',
  },
  '3333': {
    number: '3333',
    title: '3333 Angel Number',
    tagline: 'Creative Mastery and Teaching Energy',
    meaning: 'Angel number 3333 is a master call to create, teach, and share. It suggests your guides are close and that your voice, ideas, and healing capacity are ready for a larger expression.',
    spiritual: '3333 carries master-teacher energy. In Vedic terms, Jupiterian wisdom is amplified and asks to move outward through guidance, mentoring, and sacred communication.',
    love: '3333 in love points to a relationship with strong spiritual and creative chemistry. Communication and shared growth become central themes.',
    career: 'For career, 3333 highlights a calling around teaching, healing, leadership, or communication. This is not a season for hiding your gifts.',
    what_to_do: [
      'Step into teaching, mentoring, or creative leadership.',
      'Share what you know generously.',
      'Create something significant instead of waiting for perfect timing.',
      'Connect with spiritual community and aligned collaborators.',
    ],
    numerology_base: 9,
    vedic_connection: 'Guru (Jupiter) amplified: wisdom, teaching, divine support',
    colour: 'from-purple-600/20 to-violet-500/10',
    icon: 'Third Eye',
  },
};
